name: "mnist"
platform: "pytorch_libtorch"
max_batch_size: 8
dynamic_batching {}
input [
  {
    name: "INPUT__0"
    data_type: TYPE_FP32
    dims: [ 1, 28, 28 ]
  }
]
output [
  {
    name: "OUTPUT__0"
    data_type: TYPE_FP32
    dims: [ 1, 10 ]
  }
]